apiVersion: v1
kind: Service
metadata:
  name: temporal-server-service
  labels:
    app: temporal-server
spec:
  selector:
    app: temporal-server
    tier: web
  ports:
  - port: 80
    targetPort: 80
  type: NodePort